name: say_hello
description: Try dart package.
version: 0.0.2
repository: https://github.com/akulnurislam/dart-package

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
